### ISSUE TITLE
mvn test fails on local

### ISSUE THREAD

**Issue by manishmalhotrawork** [qubole/rubix#238]
tried 2 different ways: 

1. No change, logs are below..... ( with installed thrift 0.9.3 )

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[51,32] package org.apache.thrift.shaded does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java:[30,32] package org.apache.thrift.shaded does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java:[31,42] package org.apache.thrift.shaded.transport does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[196,80] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[372,14] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[425,14] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[438,57] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[466,79] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/validation/CachingValidator.java:[28,32] package org.apache.thrift.shaded does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[30,39] package org.apache.thrift.shaded.server does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[31,39] package org.apache.thrift.shaded.server does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[32,42] package org.apache.thrift.shaded.transport does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[33,42] package org.apache.thrift.shaded.transport does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[34,42] package org.apache.thrift.shaded.transport does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[56,11] cannot find symbol
  symbol:   class TServer
  location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[247,17] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[281,17] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[395,17] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[458,19] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java:[117,14] cannot find symbol
  symbol:   class TTransportException
  location: class com.qubole.rubix.bookkeeper.HeartbeatService
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java:[159,12] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.HeartbeatService
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/validation/CachingValidator.java:[134,12] cannot find symbol
  symbol:   class TException
  location: class com.qubole.rubix.bookkeeper.validation.CachingValidator
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[106,7] cannot find symbol
  symbol:   class TServerTransport
  location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[106,46] cannot find symbol
  symbol:   class TServerSocket
  location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[107,20] cannot find symbol
  symbol:   class TThreadPoolServer
  location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[108,11] package TThreadPoolServer does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[114,12] cannot find symbol
  symbol:   class TTransportException
  location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[INFO] 27 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] rubix .............................................. SUCCESS [  1.388 s]
[INFO] rubix-spi .......................................... SUCCESS [  3.777 s]
[INFO] rubix-core ......................................... SUCCESS [  1.171 s]
[INFO] rubix-common ....................................... SUCCESS [  1.351 s]
[INFO] rubix-presto ....................................... SUCCESS [  1.458 s]
[INFO] rubix-hadoop2 ...................................... SUCCESS [  1.845 s]
[INFO] rubix-bookkeeper ................................... FAILURE [  1.347 s]
[INFO] rubix-tests ........................................ SKIPPED
[INFO] assembly ........................................... SKIPPED
[INFO] rubix-rpm .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.481 s
[INFO] Finished at: 2018-11-15T14:54:00-08:00
[INFO] Final Memory: 49M/759M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project rubix-bookkeeper: Compilation failure: Compilation failure:
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[51,32] package org.apache.thrift.shaded does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java:[30,32] package org.apache.thrift.shaded does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java:[31,42] package org.apache.thrift.shaded.transport does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[196,80] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[372,14] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[425,14] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[438,57] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[466,79] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/validation/CachingValidator.java:[28,32] package org.apache.thrift.shaded does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[30,39] package org.apache.thrift.shaded.server does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[31,39] package org.apache.thrift.shaded.server does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[32,42] package org.apache.thrift.shaded.transport does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[33,42] package org.apache.thrift.shaded.transport does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[34,42] package org.apache.thrift.shaded.transport does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[56,11] cannot find symbol
[ERROR] symbol:   class TServer
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[247,17] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[281,17] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[395,17] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java:[458,19] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeper
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java:[117,14] cannot find symbol
[ERROR] symbol:   class TTransportException
[ERROR] location: class com.qubole.rubix.bookkeeper.HeartbeatService
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java:[159,12] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.HeartbeatService
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/validation/CachingValidator.java:[134,12] cannot find symbol
[ERROR] symbol:   class TException
[ERROR] location: class com.qubole.rubix.bookkeeper.validation.CachingValidator
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[106,7] cannot find symbol
[ERROR] symbol:   class TServerTransport
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[106,46] cannot find symbol
[ERROR] symbol:   class TServerSocket
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[107,20] cannot find symbol
[ERROR] symbol:   class TThreadPoolServer
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[108,11] package TThreadPoolServer does not exist
[ERROR] /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java:[114,12] cannot find symbol
[ERROR] symbol:   class TTransportException
[ERROR] location: class com.qubole.rubix.bookkeeper.BookKeeperServer
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project rubix-bookkeeper: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:858)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

2. Changed the build script to add maven repo as well.

    <repositories>
        <repository>
             <id>spring-plugins</id>
            <url>http://repo.spring.io/libs-release/</url>
        </repository>
        <repository>
                <id>maven repo</id>
                <name>maven repo</name>
                <url>https://repo.maven.apache.org/maven2</url>
        </repository>
    </repositories>

maxDisks and dirIndex are my logs to debug the issue....
looks like some cache dir is suppose to be there but removed, and still accessed coming as null.?

2018-11-15 16:39:11 [DEBUG] utils.ClusterUtil: No hostname found in etc/*-site.xml, returning localhost
 DEFAULT_DATA_CACHE_MAX_DISKS: 5
2018-11-15 16:39:11 [INFO ] validation.FileValidator:  ###### -->> maxDisks <-- ###### : 5
 DEFAULT_DATA_CACHE_MAX_DISKS: 5
2018-11-15 16:39:11 [INFO ] spi.CacheUtil:  ######### dirIndex--> ######### : 0 dirPrefixMap;: {0=/var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T//TestWorkerBookKeeper0}
 DEFAULT_DATA_CACHE_MAX_DISKS: 5
2018-11-15 16:39:11 [INFO ] spi.CacheUtil:  ######### dirIndex--> ######### : 1 dirPrefixMap;: {}
2018-11-15 16:39:11 [ERROR] validation.FileValidator: Encountered issue while verifying files
java.nio.file.NoSuchFileException: null/fcache
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)

**Comment by jordanw-bq** [comment]
Hi Manish,

1) The `rubix-spi` module shades Thrift-related classes used later on in the project; however, the shading happens in Maven's `package` phase, which is not included when running the `test` phase. We are looking into this as part of another issue as well (#186).
In the meantime, you'll need to use `mvn package` or `mvn install` to run tests.

2) We have addressed this error as part of another PR (#234). We will update this issue when the PR has been merged into `master`.

**Comment by manishmalhotrawork** [comment]
thanks @jordanw-bq 

tried mvn install , still failed.....

18/11/16 13:32:36,175 WARN bookkeeper.LocalDataTransferServer: Error in Local Data Transfer Server for client: /127.0.0.1:65035
java.lang.Exception: The requested data in not in cache. The data will be read from object store
	at com.qubole.rubix.bookkeeper.LocalDataTransferServer$ClientServiceThread.run(LocalDataTransferServer.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
18/11/16 13:32:36,176 INFO core.NonLocalReadRequestChain: Error reading data from node : localhost
java.lang.Exception: Error reading from Local Transfer Server
	at com.qubole.rubix.core.NonLocalReadRequestChain.call(NonLocalReadRequestChain.java:129)
	at com.qubole.rubix.tests.TestNonLocalReadRequestChain.test(TestNonLocalReadRequestChain.java:204)
	at com.qubole.rubix.tests.TestNonLocalReadRequestChain.testRemoteRead_WhenSomeBlocksAreCached_WithStrictMode_ParallelWarmup(TestNonLocalReadRequestChain.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
18/11/16 13:32:36,176 INFO core.NonLocalReadRequestChain: Read 250 bytes internally from node localhost
18/11/16 13:32:36,184 INFO bookkeeper.LocalDataTransferServer: Stopping Local Transfer server
18/11/16 13:32:36,186 INFO bookkeeper.BookKeeper: total free space 59626MB
18/11/16 13:32:36,194 INFO metrics.BookKeeperMetrics: Reporting metrics to Ganglia [127.0.0.1:8649]
18/11/16 13:32:36,195 INFO metrics.BookKeeperMetrics: Reporting metrics to JMX
18/11/16 13:32:36,195 INFO bookkeeper.BookKeeperServer: Starting BookKeeperServer on port 3456
18/11/16 13:32:36,390 INFO tests.TestNonLocalReadRequestChain: Waiting for BookKeeper Server to come up
18/11/16 13:32:36,391 INFO metrics.BookKeeperMetrics: Reporting metrics to Ganglia [127.0.0.1:8649]
18/11/16 13:32:36,392 INFO metrics.BookKeeperMetrics: Reporting metrics to JMX
18/11/16 13:32:36,393 INFO bookkeeper.LocalDataTransferServer: Listening on port 2222
18/11/16 13:32:36,396 INFO bookkeeper.BookKeeper: Initializing FileSystem org.apache.hadoop.fs.LocalFileSystem@622c013e for Path file:/var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T/TestNonLocalReadRequestChain/backendFile
18/11/16 13:32:36,397 INFO core.RemoteReadRequestChain: Trying to copy [0 - 100] bytes into cache from destination buffer offset 0 into localFile /var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T//TestNonLocalReadRequestChain/dir0/fcache/ar/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T/TestNonLocalReadRequestChain/backendFile
18/11/16 13:32:36,397 INFO core.RemoteReadRequestChain: Read 100 bytes from remote localFile, added 100 to destination buffer
18/11/16 13:32:36,398 INFO core.RemoteReadRequestChain: Trying to copy [100 - 200] bytes into cache from destination buffer offset 0 into localFile /var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T//TestNonLocalReadRequestChain/dir0/fcache/ar/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T/TestNonLocalReadRequestChain/backendFile
18/11/16 13:32:36,398 INFO core.RemoteReadRequestChain: Read 100 bytes from remote localFile, added 100 to destination buffer
18/11/16 13:32:36,399 INFO core.RemoteReadRequestChain: Trying to copy [200 - 300] bytes into cache from destination buffer offset 0 into localFile /var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T//TestNonLocalReadRequestChain/dir0/fcache/ar/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T/TestNonLocalReadRequestChain/backendFile
18/11/16 13:32:36,399 INFO core.RemoteReadRequestChain: Read 100 bytes from remote localFile, added 100 to destination buffer
18/11/16 13:32:36,400 INFO core.RemoteReadRequestChain: Trying to copy [300 - 400] bytes into cache from destination buffer offset 0 into localFile /var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T//TestNonLocalReadRequestChain/dir0/fcache/ar/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T/TestNonLocalReadRequestChain/backendFile
18/11/16 13:32:36,400 INFO core.RemoteReadRequestChain: Read 100 bytes from remote localFile, added 100 to destination buffer
18/11/16 13:32:36,401 INFO core.RemoteReadRequestChain: Trying to copy [400 - 500] bytes into cache from destination buffer offset 0 into localFile /var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T//TestNonLocalReadRequestChain/dir0/fcache/ar/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T/TestNonLocalReadRequestChain/backendFile
18/11/16 13:32:36,401 INFO core.RemoteReadRequestChain: Read 100 bytes from remote localFile, added 100 to destination buffer
18/11/16 13:32:36,403 INFO bookkeeper.LocalDataTransferServer: Stopping Local Transfer server
18/11/16 13:32:36,403 INFO metrics.BookKeeperMetrics: Reporting metrics to Ganglia [127.0.0.1:8649]
18/11/16 13:32:36,403 INFO metrics.BookKeeperMetrics: Reporting metrics to JMX
18/11/16 13:32:36,404 INFO bookkeeper.BookKeeper: total free space 59626MB
18/11/16 13:32:36,404 INFO bookkeeper.LocalDataTransferServer: Listening on port 2222
18/11/16 13:32:36,404 INFO metrics.BookKeeperMetrics: Reporting metrics to Ganglia [127.0.0.1:8649]
18/11/16 13:32:36,404 INFO metrics.BookKeeperMetrics: Reporting metrics to JMX
18/11/16 13:32:36,405 INFO bookkeeper.BookKeeperServer: Starting BookKeeperServer on port 3456
18/11/16 13:32:36,612 INFO core.NonLocalReadRequestChain: Read 50 bytes internally from node localhost
18/11/16 13:32:36,614 INFO core.NonLocalReadRequestChain: Read 150 bytes internally from node localhost
18/11/16 13:32:36,616 INFO core.NonLocalReadRequestChain: Read 250 bytes internally from node localhost
18/11/16 13:32:36,618 ERROR bookkeeper.LocalDataTransferServer: The requested data for block 6 of file file:/var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T/TestNonLocalReadRequestChain/backendFile in not in cache.  The data will be read from object store
18/11/16 13:32:36,618 WARN bookkeeper.LocalDataTransferServer: Error in Local Data Transfer Server for client: /127.0.0.1:65044
java.lang.Exception: The requested data in not in cache. The data will be read from object store
	at com.qubole.rubix.bookkeeper.LocalDataTransferServer$ClientServiceThread.run(LocalDataTransferServer.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
18/11/16 13:32:36,618 INFO core.NonLocalReadRequestChain: Error reading data from node : localhost
java.lang.Exception: Error reading from Local Transfer Server
	at com.qubole.rubix.core.NonLocalReadRequestChain.call(NonLocalReadRequestChain.java:129)
	at com.qubole.rubix.tests.TestNonLocalReadRequestChain.test(TestNonLocalReadRequestChain.java:204)
	at com.qubole.rubix.tests.TestNonLocalReadRequestChain.testRemoteRead_WhenSomeBlocksAreCached_WithoutStrictMode_ParallelWarmup(TestNonLocalReadRequestChain.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
18/11/16 13:32:36,619 INFO core.DirectReadRequestChain: Read 100 bytes directly from remote, no caching
18/11/16 13:32:36,619 INFO core.NonLocalReadRequestChain: Read 250 bytes internally from node localhost
18/11/16 13:32:36,620 INFO bookkeeper.LocalDataTransferServer: Stopping Local Transfer server
18/11/16 13:32:36,621 INFO tests.TestNonLocalReadRequestChain: Deleting files in /var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T//TestNonLocalReadRequestChain/dir0
18/11/16 13:32:36,623 INFO tests.TestThriftServerJVM: Test Directory : /var/folders/fw/q69qg32x4tj87bj2_thdycg00000gn/T//TestThriftServerJVM/dir0
Tests run: 18, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 13.079 sec <<< FAILURE!
setupClass(com.qubole.rubix.tests.TestThriftServerJVM)  Time elapsed: 0.24 sec  <<< FAILURE!
java.lang.NullPointerException
	at com.qubole.rubix.tests.TestThriftServerJVM.setupClass(TestThriftServerJVM.java:87)


Results :

Failed tests:   setupClass(com.qubole.rubix.tests.TestThriftServerJVM)

Tests run: 18, Failures: 1, Errors: 0, Skipped: 7

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] rubix .............................................. SUCCESS [  2.310 s]
[INFO] rubix-spi .......................................... SUCCESS [  5.126 s]
[INFO] rubix-core ......................................... SUCCESS [  2.418 s]
[INFO] rubix-common ....................................... SUCCESS [  2.219 s]
[INFO] rubix-presto ....................................... SUCCESS [  2.221 s]
[INFO] rubix-hadoop2 ...................................... SUCCESS [  2.592 s]
[INFO] rubix-bookkeeper ................................... SUCCESS [ 26.816 s]
[INFO] rubix-tests ........................................ FAILURE [ 14.222 s]
[INFO] assembly ........................................... SKIPPED
[INFO] rubix-rpm .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 58.064 s
[INFO] Finished at: 2018-11-16T13:32:37-08:00
[INFO] Final Memory: 69M/1134M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project rubix-tests: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/mmalhotra2/Documents/git/rubix2/rubix/rubix-tests/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by abhishekdas99** [comment]
@manishmalhotrawork The test that is failing has dependency on hadoop installation. You should have hadoop installed at `/usr/lib/hadoop2/bin/hadoop`
Otherwise you can turn these tests off by setting the following in class TestThriftServerJVM.java

```
@Test(enabled = false)
public void testBookKeeperCaching()

```
and 

```
@Test(enabled = false, expectedExceptions = org.apache.thrift.shaded.transport.TTransportException.class)
public void testCreateBookKeeperClient_OnNotRunningPort()
```

**Comment by manishmalhotrawork** [comment]
thanks @abhishekdas99 ! will try that.
meanwhile I build by disabling the tests.

If you are part of the authors/qubole then I have few more questions:

1. I also created another issue: basically looking for : "guide to use rubix with S3 and HDFS"
We want to evaluate Rubix and Auxillio and other products for caching layer, and I see Rubix is light-weight which is a huge plus point.
So, any presentations/documentation will be appreciated ! 

2. Rubix is open-source, but what is the exact license we have, and how to contribute if we want.
